# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        ma_vignette:
            quality: 75
            filters:
                thumbnail: { size: [ 150,150 ], mode: outbound }

        petite_vignette:
            quality: 45
            filters:
                thumbnail: { size: [ 30,30 ], mode: outbound }

